# -*- coding: utf-8 -*-
"""Videodownloader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RfxfyurOHOA4ye_-dLGTUABS6BwfDf0Z
"""

!pip install pytube yt-dlp

import os

# Video URL'sini girin
video_url = input("YouTube Video URL'sini girin: ")

# İndirme işlemi
print("Video indiriliyor...")
os.system(f"yt-dlp -o '/content/%(title)s.%(ext)s' {video_url}")
print("İndirme tamamlandı! Dosya /content/ klasöründe saklanıyor.")